server:
  port: 8761

spring:
  application:
    name: eurekaserver
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expor todos os endpoints de gerenciamento através da web
  health:
    readiness-state:
      enabled: true  # Habilitar o estado de readiness
    liveness-state:
      enabled: true # Habilitar o estado de liveness
  endpoint:
    health:
      probes:
        enabled: true  Habilitar probes de saúde (health checks)
