server:
  port: 8080

spring:
  application:
    name: temperature
  jpa:
    open-in-view: true
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    database-platform=org:
      hibernate:
        dialect: H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expor todos os endpoints de gerenciamento através da web
  health:
    readiness-state:
      enabled: true  # Habilitar o estado de readiness
    liveness-state:
      enabled: true # Habilitar o estado de liveness
  endpoint:
    health:
      probes:
        enabled: true  # Habilitar probes de saúde (health checks)
